---
- name: Ensure latest java-1.8.0 is installed
  yum:
    name: java-1.8.0
    state: latest
    update_cache: yes
  tags: install

- name: Ensure java profile
  template:
    src: java.sh.j2
    dest: /etc/profile.d/java.sh
    mode: 0644
  tags: config

