---
- name: Download Grafana
  when: not download_from_s3 | default(false)
  get_url:
    url: "https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-{{ grafana_version }}-1.x86_64.rpm"
    dest: "{{ grafana_dest }}"
    mode: 0755

- name: Download Grafana from S3
  when: download_from_s3 | default(false)
  include_role:
    name: get_s3
  vars:
    get_s3_src: "{{ grafana_filename }}"
    get_s3_dest: "{{ grafana_dest }}/{{ grafana_filename }}"
    get_s3_overwrite: different
  tags: [ download ]

- name: install grafana rpm from a local file
  yum:
    name: "{{ grafana_dest }}/{{ grafana_filename }}"
    state: present
