---
# tasks file for accounts

- include: create.yml
  tags: create
- include: delete.yml
  tags: delete

- name: Update login.defs
  template: src=login.defs.j2 dest=/etc/login.defs owner=root group=root mode=0644
  tags: config

