---
- name: Update InfluxDB Directory Permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ influxdb_user }}"
    group: "{{ influxdb_user }}"
    mode: "0755"
  loop:
    - "{{ influxdb_log_dir }}"
    - "{{ influxdb_lib_dir }}"

- name: copy startup scripts
  template: src="{{ item.src }}" dest="{{ item.dest }}" owner="root" group="root" mode='0755'
  with_items:
    - { src: 'influxdb.sh.j2', dest: "/etc/init.d/influxdb" }

- name: copy influxdb configs
  template: src="{{ item.src }}" dest="{{ item.dest }}" owner="{{ influxdb_user }}" group="{{ influxdb_user }}" mode='0640'
  with_items:
    - { src: 'influxdb.conf.j2', dest: "{{influxdb_conf_dir}}/influxdb.conf" }
  notify:
    - restart influxdb
