---
# tasks file for mongo

- name: Add repository
  yum_repository:
    name: mongodb-org-{{ mongo_version }}
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongo_version }}/$basearch/
    gpgcheck: no
  tags: [ yum ]
  when: local_artifact is undefined

- name: install mongo
  yum:
    name: mongodb-org
    state: latest
  tags: [ yum ]
  when: local_artifact is undefined

- name: install mongo from local packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ mongo_server_rpm_name }}"
    - "{{ mongo_shell_rpm_name }}"
    - "{{ mongo_tools_rpm_name }}"
  tags: [ yum ]
  when: local_artifact is defined

- name: ensure conf directories exist
  file: path="{{ item }}" state=directory owner="{{ mongo_user }}" group="{{ mongo_user }}" mode=0755
  with_items:
    - "{{ mongo_db_dir }}"
  tags: [ dep ]

- name: Ensure SELinux context on data directory
  command: chcon -R -u system_u -t mongod_var_lib_t {{ mongo_db_dir }}
  when: selinux_enabled | default(true)
  changed_when: false
  tags: selinux

- name: Ensure SELinux access to mongo port
  command: semanage port -a -t mongod_port_t -p tcp {{ mongo_port }}
  when: selinux_enabled | default(true)
  tags: selinux
  changed_when: false
  ignore_errors: yes

- name: copy system configs
  template: src="{{ item.src }}" dest="{{ item.dest }}" owner='root' group='root' mode='0644'
  with_items:
    - { src: '99-mongodb-nproc.conf.j2', dest: '/etc/security/limits.d/99-mongodb-nproc.conf' }
  tags: [ install, config ]

- name: copy mongo configs
  template: src="{{ item.src }}" dest="{{ item.dest }}" mode='0644'
  with_items:
    - { src: 'mongod.yaml.j2', dest: "{{ mongo_conf_file }}" }
  notify:
    - restart mongod
  tags: [ install, config ]

- name: Start mongo service (service mongod start)
  service: name=mongod state=started enabled=yes
